// Generated by GitHub Copilot
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        dragon: {
          navy: "#081522",
          navySoft: "#10263a",
          red: "#e53935",
          redGlow: "#ff6b6b",
          sand: "#f5f0e6",
        },
      },
      boxShadow: {
        glow: "0 0 30px rgba(229, 57, 53, 0.35)",
      },
      fontFamily: {
        display: ["'Space Grotesk'", "sans-serif"],
      },
      keyframes: {
        floatIn: {
          "0%": { opacity: 0, transform: "translateY(16px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
      },
      animation: {
        floatIn: "floatIn 600ms ease-out forwards",
      },
    },
  },
  plugins: [],
};
