// Generated by GitHub Copilot
(function initThemeEarly() {
  try {
    var saved = localStorage.getItem("theme");
    var mode = saved || "dark";
    document.documentElement.setAttribute("data-theme", mode);
  } catch (_error) {
    document.documentElement.setAttribute("data-theme", "dark");
  }
})();
