// Generated by GitHub Copilot
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

const pagesBasePath = process.env.VITE_BASE_PATH || "/dragon-portfolio/";
const isProductionBuild = process.env.NODE_ENV === "production";

export default defineConfig({
  plugins: [react()],
  base: isProductionBuild ? pagesBasePath : "/",
  server: {
    host: true,
    proxy: {
      "/api": {
        target: "http://127.0.0.1:8080",
        changeOrigin: true,
      },
    },
  },
  build: {
    target: "es2022",
    sourcemap: true,
  },
});
