// Generated by GitHub Copilot
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["src/**/*.test.{js,jsx}"],
    environment: "node",
    globals: true,
    coverage: {
      provider: "v8",
      reporter: ["text", "lcov"],
      include: ["src/utils/**/*.js"],
      thresholds: {
        lines: 55,
        functions: 80,
        branches: 40,
        statements: 55,
      },
    },
  },
});
