// Generated by GitHub Copilot
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["src/**/*.test.{js,jsx}"],
    environment: "node",
    globals: true,
  },
});
