// Generated by GitHub Copilot
import { useEffect, useState } from "react";
import profileFallback from "../data/profileFallback";
import { buildApiUrl } from "../utils/api";

/**
 * Load portfolio profile payload from backend and provide resilient fallback data.
 *
 * @returns {{data: Record<string, any>, loading: boolean, error: string}} Hook state.
 */
export default function usePortfolioData() {
  const [data, setData] = useState(profileFallback);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const controller = new AbortController();

    /**
     * Fetch profile payload with abort support and safe fallback behavior.
     */
    async function loadProfile() {
      try {
        const response = await fetch(buildApiUrl("/profile"), {
          signal: controller.signal,
        });

        if (!response.ok) {
          throw new Error(`Profile request failed with status ${response.status}`);
        }

        const payload = await response.json();
        setData(payload);
        setError("");
      } catch (fetchError) {
        if (fetchError.name === "AbortError") {
          return;
        }

        setData(profileFallback);
        setError("Live profile data is unavailable right now. Showing fallback profile data.");
      } finally {
        setLoading(false);
      }
    }

    loadProfile();

    return () => {
      controller.abort();
    };
  }, []);

  return { data, loading, error };
}
