// Generated by GitHub Copilot
import { useEffect, useState } from "react";
import profileFallback from "../data/profileFallback";
import { buildApiUrl } from "../utils/api";

/**
 * Load portfolio profile payload from backend and provide resilient fallback data.
 *
 * @returns {{data: Record<string, any>, loading: boolean, error: string}} Hook state.
 */
export default function usePortfolioData() {
  const [data, setData] = useState(profileFallback);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    let isMounted = true;
    let intervalId;

    /**
     * Load profile payload and optionally preserve current UI state on transient failures.
     *
     * @param {{silent?: boolean}} options Fetch behavior options.
     */
    async function loadProfile(options = {}) {
      const { silent = false } = options;

      try {
        const response = await fetch(buildApiUrl("/profile"));

        if (!response.ok) {
          throw new Error(`Profile request failed with status ${response.status}`);
        }

        const payload = await response.json();
        if (!isMounted) {
          return;
        }

        setData(payload);
        setError("");
      } catch (fetchError) {
        if (!isMounted || fetchError.name === "AbortError") {
          return;
        }

        if (!silent) {
          setData(profileFallback);
          setError("Live profile data is unavailable right now. Showing fallback profile data.");
        }
      } finally {
        if (isMounted) {
          setLoading(false);
        }
      }
    }

    loadProfile();

    // Keep profile data near-real-time while respecting resource efficiency.
    intervalId = window.setInterval(() => {
      loadProfile({ silent: true });
    }, 45_000);

    /**
     * Refresh data when the tab becomes active again.
     */
    function handleForegroundRefresh() {
      if (document.visibilityState === "visible") {
        loadProfile({ silent: true });
      }
    }

    document.addEventListener("visibilitychange", handleForegroundRefresh);
    window.addEventListener("focus", handleForegroundRefresh);

    return () => {
      isMounted = false;
      if (intervalId) {
        window.clearInterval(intervalId);
      }
      document.removeEventListener("visibilitychange", handleForegroundRefresh);
      window.removeEventListener("focus", handleForegroundRefresh);
    };
  }, []);

  return { data, loading, error };
}
