// Generated by GitHub Copilot
const cacheStore = new Map();

/**
 * Read a cached value or compute and cache it for a fixed TTL.
 * This avoids repeated upstream API calls and reduces network waste.
 *
 * @param {string} key Cache key.
 * @param {number} ttlMs Time to keep value in cache.
 * @param {() => Promise<any>} computeFn Async producer when cache is stale.
 * @returns {Promise<any>} Cached or computed value.
 */
export async function getCachedOrCompute(key, ttlMs, computeFn) {
  const cached = cacheStore.get(key);
  const now = Date.now();

  if (cached && cached.expiresAt > now) {
    return cached.value;
  }

  const value = await computeFn();
  cacheStore.set(key, {
    value,
    expiresAt: now + ttlMs,
  });

  return value;
}

/**
 * Clear all cached values.
 * Useful for tests and local troubleshooting.
 */
export function clearCache() {
  cacheStore.clear();
}
