// Generated by GitHub Copilot
import crypto from "node:crypto";

import cors from "cors";
import "dotenv/config";
import express from "express";
import rateLimit from "express-rate-limit";
import helmet from "helmet";
import Parser from "rss-parser";
import { z } from "zod";
import { getCachedOrCompute } from "./cache.js";
import linkedinProfile from "./data/linkedinProfile.js";

const app = express();
const feedParser = new Parser();
const port = Number.parseInt(process.env.PORT || "8080", 10);
const anthropicModel = process.env.ANTHROPIC_MODEL || "claude-sonnet-4-20250514";
const anthropicFastModel = process.env.ANTHROPIC_FAST_MODEL || "claude-3-5-haiku-latest";
const corsOrigins = parseCorsOrigins(process.env.CORS_ORIGINS);
const githubUsername = process.env.GITHUB_USERNAME || "Ramdragneel01";
const mediumUsername = process.env.MEDIUM_USERNAME || "RamPrakashD";
const mediumTotalArticlesFallback = parsePositiveInteger(process.env.MEDIUM_TOTAL_ARTICLES, 10);
const chatMaxTokens = parsePositiveInteger(process.env.CHAT_MAX_TOKENS, 300);
const chatHistoryCharBudget = parsePositiveInteger(process.env.CHAT_HISTORY_CHAR_BUDGET, 1800);
const chatFastModelThreshold = parsePositiveInteger(process.env.CHAT_FAST_MODEL_CHAR_THRESHOLD, 260);
const defaultChatSystemPrompt =
  "You are a concise assistant for Ram's portfolio. Prioritize factual project summaries and practical impact.";

const apiLimiter = rateLimit({
  windowMs: 60_000,
  max: Number.parseInt(process.env.API_RATE_LIMIT_PER_MINUTE || "120", 10),
  standardHeaders: true,
  legacyHeaders: false,
  message: {
    error: "Too many requests. Please retry in a minute.",
  },
});

const chatLimiter = rateLimit({
  windowMs: 60_000,
  max: Number.parseInt(process.env.CHAT_RATE_LIMIT_PER_MINUTE || "30", 10),
  standardHeaders: true,
  legacyHeaders: false,
  message: {
    error: "Chat rate limit exceeded. Please retry in a minute.",
  },
});

const contactLimiter = rateLimit({
  windowMs: 3_600_000,
  max: Number.parseInt(process.env.CONTACT_RATE_LIMIT_PER_HOUR || "10", 10),
  standardHeaders: true,
  legacyHeaders: false,
  message: {
    error: "Contact rate limit exceeded. Please retry later.",
  },
});

app.use(
  helmet({
    crossOriginResourcePolicy: { policy: "cross-origin" },
  })
);
app.use(
  cors({
    origin: (origin, callback) => {
      if (isOriginAllowed(origin)) {
        callback(null, true);
        return;
      }
      callback(new Error("Origin not allowed by CORS policy"));
    },
    methods: ["GET", "POST"],
  })
);
app.use(express.json({ limit: "200kb" }));
app.use("/api", apiLimiter);

app.use((req, res, next) => {
  const requestId = req.header("X-Request-ID") || crypto.randomUUID();
  req.requestId = requestId;
  res.setHeader("X-Request-ID", requestId);

  const startTime = Date.now();
  res.on("finish", () => {
    logRequest(req, res.statusCode, startTime);
  });

  next();
});

const chatInputSchema = z
  .object({
    message: z.string().trim().min(1).max(1000).optional(),
    question: z.string().trim().min(1).max(1000).optional(),
    systemPrompt: z.string().trim().max(500).optional(),
    history: z
      .array(
        z.object({
          role: z.enum(["user", "assistant"]),
          content: z.string().trim().min(1).max(500),
        })
      )
      .max(6)
      .optional(),
  })
  .refine((payload) => Boolean(payload.message || payload.question), {
    message: "Either message or question must be provided.",
  });

const contactInputSchema = z.object({
  name: z.string().trim().min(2).max(120),
  email: z.string().trim().email(),
  message: z.string().trim().min(10).max(4000),
});

app.get("/health", (_req, res) => {
  res.json({
    status: "ok",
    service: "dragon-portfolio-api",
    model: anthropicModel,
    timestamp: new Date().toISOString(),
  });
});

app.get("/api/health", (_req, res) => {
  res.json({
    status: "ok",
    service: "dragon-portfolio-api",
    model: anthropicModel,
    timestamp: new Date().toISOString(),
  });
});

/**
 * Return normalized profile payload merged from static LinkedIn context
 * and live Medium/GitHub profile feeds.
 */
app.get("/api/profile", async (req, res) => {
  try {
    const payload = await getProfilePayload();
    res.json(payload);
  } catch {
    res.status(502).json({
      error: "Could not build profile payload",
      requestId: req.requestId,
    });
  }
});

/**
 * Handle chat prompt requests and proxy to Anthropic with server-side credentials.
 */
app.post("/api/chat", chatLimiter, async (req, res) => {
  const parsedBody = chatInputSchema.safeParse(req.body);
  if (!parsedBody.success) {
    res.status(400).json({
      error: "Invalid chat request payload",
      details: parsedBody.error.flatten(),
      requestId: req.requestId,
    });
    return;
  }

  const prompt = parsedBody.data.message || parsedBody.data.question;
  const requestHistory = parsedBody.data.history || [];

  if (!process.env.ANTHROPIC_API_KEY) {
    const localReply = buildLocalPortfolioReply(prompt);
    res.json({
      content: localReply,
      reply: localReply,
      model: "local-portfolio-fallback",
      fallback: true,
      requestId: req.requestId,
    });
    return;
  }

  try {
    const { content, model } = await sendAnthropicRequest(
      prompt,
      parsedBody.data.systemPrompt,
      req.requestId,
      requestHistory
    );
    res.json({
      content,
      reply: content,
      model,
      requestId: req.requestId,
    });
  } catch {
    const localReply = buildLocalPortfolioReply(prompt);
    res.json({
      content: localReply,
      reply: localReply,
      model: "local-portfolio-fallback",
      fallback: true,
      degraded: true,
      requestId: req.requestId,
    });
  }
});

/**
 * Handle contact form submissions and proxy to EmailJS from the server.
 */
app.post("/api/contact", contactLimiter, async (req, res) => {
  const parsedBody = contactInputSchema.safeParse(req.body);
  if (!parsedBody.success) {
    res.status(400).json({
      error: "Invalid contact request payload",
      details: parsedBody.error.flatten(),
      requestId: req.requestId,
    });
    return;
  }

  const serviceId = process.env.EMAILJS_SERVICE_ID;
  const templateId = process.env.EMAILJS_TEMPLATE_ID;
  const publicKey = process.env.EMAILJS_PUBLIC_KEY;

  if (!serviceId || !templateId || !publicKey) {
    res.status(503).json({
      error: "Contact service is not configured",
      requestId: req.requestId,
    });
    return;
  }

  try {
    const response = await fetch("https://api.emailjs.com/api/v1.0/email/send", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        service_id: serviceId,
        template_id: templateId,
        user_id: publicKey,
        template_params: {
          from_name: sanitizeText(parsedBody.data.name, 120),
          from_email: sanitizeText(parsedBody.data.email, 150),
          message: sanitizeText(parsedBody.data.message, 2000),
        },
      }),
    });

    if (!response.ok) {
      throw new Error(`EmailJS request failed: ${response.status}`);
    }

    res.json({
      status: "sent",
      requestId: req.requestId,
    });
  } catch {
    res.status(502).json({
      error: "Could not deliver message at this time",
      requestId: req.requestId,
    });
  }
});

app.use((error, req, res, next) => {
  if (error?.message === "Origin not allowed by CORS policy") {
    res.status(403).json({
      error: "Origin is not allowed",
      requestId: req.requestId,
    });
    return;
  }

  next(error);
});

app.listen(port, () => {
  console.log(`[dragon-portfolio-api] listening on port ${port}`);
});

/**
 * Parse a comma-separated CORS origin string into an allowlist set.
 */
function parseCorsOrigins(originInput) {
  return new Set(
    (originInput || "http://127.0.0.1:5173,http://localhost:5173")
      .split(",")
      .map((origin) => origin.trim())
      .filter(Boolean)
  );
}

/**
 * Parse an integer env value and fallback if invalid or non-positive.
 */
function parsePositiveInteger(value, fallback) {
  const parsed = Number.parseInt(value || "", 10);
  if (Number.isNaN(parsed) || parsed <= 0) {
    return fallback;
  }

  return parsed;
}

/**
 * Check if a request origin is allowed by explicit list or Vercel previews.
 */
function isOriginAllowed(origin) {
  if (!origin) {
    return true;
  }

  if (corsOrigins.has(origin)) {
    return true;
  }

  return origin.endsWith(".vercel.app");
}

/**
 * Normalize user text inputs by reducing whitespace and max length.
 */
function sanitizeText(value, maxLength) {
  return String(value).replace(/\s+/g, " ").trim().slice(0, maxLength);
}

// Generated by GitHub Copilot
/**
 * Collect concise experience highlights matching query terms.
 *
 * @param {Array<{company?: string, role?: string, highlights?: string[]}>} entries Experience entries.
 * @param {string[]} terms Lowercase query terms to match.
 * @param {number} maxItems Maximum returned highlights.
 * @returns {string[]} Matched and formatted highlights.
 */
function collectExperienceHighlights(entries, terms, maxItems = 2) {
  const safeEntries = Array.isArray(entries) ? entries : [];
  const safeTerms = Array.isArray(terms) ? terms.filter(Boolean) : [];
  const results = [];

  for (const entry of safeEntries) {
    if (!entry || results.length >= maxItems) {
      continue;
    }

    const company = sanitizeText(entry.company || "", 120);
    const role = sanitizeText(entry.role || "", 120);
    const safeHighlights = Array.isArray(entry.highlights) ? entry.highlights : [];

    for (const rawHighlight of safeHighlights) {
      if (results.length >= maxItems) {
        break;
      }

      const highlight = sanitizeText(rawHighlight || "", 200);
      if (!highlight) {
        continue;
      }

      const searchableText = `${company} ${role} ${highlight}`.toLowerCase();
      const isMatch = safeTerms.some((term) => searchableText.includes(term));
      if (!isMatch) {
        continue;
      }

      results.push(`At ${company || "recent roles"}: ${highlight}`);
    }
  }

  return results;
}

// Generated by GitHub Copilot
/**
 * Build a deterministic local portfolio reply when upstream chat is unavailable.
 *
 * @param {string} message User message.
 * @returns {string} Human-readable answer sourced from local profile data.
 */
function buildLocalPortfolioReply(message) {
  const query = sanitizeText(message || "", 1000).toLowerCase();
  const identity = linkedinProfile?.identity || {};
  const experience = Array.isArray(linkedinProfile?.experience) ? linkedinProfile.experience : [];
  const topSkills = Array.isArray(linkedinProfile?.topSkills) ? linkedinProfile.topSkills : [];
  const languages = Array.isArray(linkedinProfile?.languages) ? linkedinProfile.languages : [];
  const certifications = Array.isArray(linkedinProfile?.certifications)
    ? linkedinProfile.certifications
    : [];
  const volunteerExperience = Array.isArray(linkedinProfile?.volunteerExperience)
    ? linkedinProfile.volunteerExperience
    : [];
  const hackathons = Array.isArray(linkedinProfile?.hackathons)
    ? linkedinProfile.hackathons
    : [];
  const linkedinProjects = Array.isArray(linkedinProfile?.linkedinProjects)
    ? linkedinProfile.linkedinProjects
    : [];

  const hasTerm = (...terms) => terms.some((term) => query.includes(term));

  if (!query) {
    return "I can help with Ram's experience, skills, certifications, projects, or contact details.";
  }

  if (hasTerm("react", "next.js", "nextjs", "frontend", "ui", "javascript", "mern")) {
    const matched = collectExperienceHighlights(
      experience,
      ["react", "next.js", "frontend", "website", "migration"],
      3
    );

    if (matched.length) {
      return `Yes. Ram has React and frontend experience. ${matched.join(" ")}`;
    }

    return "Yes. Ram has frontend experience, including React and modern UI engineering across product delivery roles.";
  }

  if (hasTerm("skill", "skills", "tech stack", "technology", "technologies")) {
    const skillSummary = topSkills
      .slice(0, 4)
      .map((skill) => `${sanitizeText(skill.name || "", 80)} (${skill.level || 0}%)`)
      .join(", ");
    const headline = sanitizeText(identity.headline || "", 220);

    return `Top skills include ${skillSummary || "Python, Machine Learning, and frontend engineering"}. Headline: ${headline}`;
  }

  if (hasTerm("experience", "exp", "background", "work", "career")) {
    const summary = experience
      .slice(0, 3)
      .map(
        (item) =>
          `${sanitizeText(item.role || "", 90)} at ${sanitizeText(item.company || "", 90)} (${sanitizeText(item.period || "", 60)})`
      )
      .join("; ");
    return `Recent experience: ${summary}`;
  }

  if (hasTerm("cert", "certification", "pmle", "google cloud")) {
    const certSummary = certifications.slice(0, 3).map((item) => sanitizeText(item, 140)).join("; ");
    return `Certifications include: ${certSummary}`;
  }

  if (hasTerm("language", "languages", "speak")) {
    const languageSummary = languages
      .map((item) => `${sanitizeText(item.name || "", 40)} (${sanitizeText(item.proficiency || "", 60)})`)
      .join(", ");
    return `Languages: ${languageSummary}`;
  }

  if (hasTerm("volunteer", "volunteering", "community")) {
    if (!volunteerExperience.length) {
      return "Volunteer entries are not currently available in the synced dataset.";
    }

    const volunteerSummary = volunteerExperience
      .slice(0, 3)
      .map(
        (item) =>
          `${sanitizeText(item.role || "", 90)} at ${sanitizeText(item.organization || "", 90)} (${sanitizeText(item.period || "", 60)})`
      )
      .join("; ");

    return `Volunteer highlights: ${volunteerSummary}`;
  }

  if (hasTerm("hackathon", "hackathons", "competition")) {
    if (!hackathons.length) {
      return "Hackathon entries are not currently available in the synced dataset.";
    }

    const hackathonSummary = hackathons
      .slice(0, 3)
      .map((item) => sanitizeText(item.name || "", 120))
      .join("; ");

    return `Hackathon highlights: ${hackathonSummary}`;
  }

  if (hasTerm("contact", "email", "linkedin", "phone", "mobile", "reach")) {
    const contact = linkedinProfile?.contact || {};
    return `You can reach Ram via email ${sanitizeText(contact.email || "", 120)}, LinkedIn ${sanitizeText(contact.linkedin || "", 180)}, GitHub ${sanitizeText(contact.github || "", 180)}, and Medium ${sanitizeText(contact.medium || "", 180)}.`;
  }

  if (hasTerm("project", "projects", "github", "repo", "repository")) {
    const githubUrl = sanitizeText(linkedinProfile?.contact?.github || "", 180);
    const linkedinProjectSummary = linkedinProjects
      .slice(0, 2)
      .map((project) => sanitizeText(project.title || "", 100))
      .join(" and ");

    if (linkedinProjectSummary) {
      return `Ram's project portfolio is available on GitHub: ${githubUrl}. LinkedIn-only project highlights include ${linkedinProjectSummary}.`;
    }

    return `Ram's project portfolio is available on GitHub: ${githubUrl}. I can also summarize specific project areas like MLOps, reliability, or frontend architecture.`;
  }

  const summary = sanitizeText(identity.summary || "", 260);
  return `${summary} Ask me about experience, React/frontend work, skills, certifications, or projects.`;
}

/**
 * Build GitHub API headers with optional token support.
 */
function getGithubHeaders() {
  const headers = {
    Accept: "application/vnd.github+json",
    "User-Agent": "dragon-portfolio-service",
  };

  if (process.env.GITHUB_TOKEN) {
    headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;
  }

  return headers;
}

/**
 * Remove common Markdown syntax from text for concise UI summaries.
 *
 * @param {string} markdown Raw markdown content.
 * @returns {string} Plain text candidate.
 */
function stripMarkdown(markdown) {
  return String(markdown || "")
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/`[^`]*`/g, " ")
    .replace(/!\[[^\]]*\]\([^)]*\)/g, " ")
    .replace(/\[[^\]]*\]\([^)]*\)/g, " ")
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/[*_~>#-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Fetch and normalize README summary text for a GitHub repository.
 *
 * @param {string} owner Repository owner.
 * @param {string} repoName Repository name.
 * @returns {Promise<string>} Short summary when available.
 */
async function fetchGithubReadmeSummary(owner, repoName) {
  try {
    const response = await fetch(`https://api.github.com/repos/${owner}/${repoName}/readme`, {
      headers: getGithubHeaders(),
    });

    if (!response.ok) {
      return "";
    }

    const payload = await response.json();
    if (!payload?.content) {
      return "";
    }

    const markdownText = Buffer.from(payload.content, "base64").toString("utf8");
    const plainText = stripMarkdown(markdownText);
    return sanitizeText(plainText, 240);
  } catch {
    return "";
  }
}

/**
 * Fetch profile and repository metadata from GitHub.
 */
async function fetchGithubPayload() {
  const [profileResponse, repositoriesResponse] = await Promise.all([
    fetch(`https://api.github.com/users/${githubUsername}`, {
      headers: getGithubHeaders(),
    }),
    fetch(`https://api.github.com/users/${githubUsername}/repos?sort=updated&per_page=8&type=owner`, {
      headers: getGithubHeaders(),
    }),
  ]);

  if (!profileResponse.ok || !repositoriesResponse.ok) {
    throw new Error("GitHub profile request failed");
  }

  const profile = await profileResponse.json();
  const repositories = await repositoriesResponse.json();
  const repositoryOwner = profile?.login || githubUsername;
  const normalizedRepos = Array.isArray(repositories)
    ? await Promise.all(
        repositories.map(async (repo) => {
          const readmeSummary = await fetchGithubReadmeSummary(repositoryOwner, repo.name);
          return {
            id: String(repo.id),
            title: repo.name,
            description: repo.description || "No description provided yet.",
            readmeSummary,
            github: repo.html_url,
            tags: [repo.language, ...(repo.topics || [])].filter(Boolean).slice(0, 4),
            stars: repo.stargazers_count || 0,
            forks: repo.forks_count || 0,
            updatedAt: repo.updated_at || "",
          };
        })
      )
    : [];

  normalizedRepos.sort((left, right) => {
    const leftPriority = String(left.title || "").toLowerCase() === "partner-portal-microfrontends" ? 0 : 1;
    const rightPriority = String(right.title || "").toLowerCase() === "partner-portal-microfrontends" ? 0 : 1;
    return leftPriority - rightPriority;
  });

  return {
    profile: {
      username: profile.login,
      avatarUrl: profile.avatar_url || "",
      followers: profile.followers || 0,
      following: profile.following || 0,
      publicRepos: profile.public_repos || 0,
      bio: profile.bio || "",
      profileUrl: profile.html_url || `https://github.com/${githubUsername}`,
    },
    repos: normalizedRepos,
  };
}

/**
 * Fetch and normalize latest Medium articles through RSS feed.
 */
async function fetchMediumPayload() {
  const feed = await feedParser.parseURL(`https://medium.com/feed/@${mediumUsername}`);
  const feedItems = Array.isArray(feed.items) ? feed.items : [];
  const articles = feedItems.slice(0, 6).map((item, index) => ({
    id: item.guid || item.link || `${item.title || "article"}-${index}`,
    title: item.title || "Untitled article",
    link: item.link || `https://medium.com/@${mediumUsername}`,
    excerpt: sanitizeText(item.contentSnippet || item.content || "", 200),
    publishedAt: item.isoDate || item.pubDate || "",
    categories: (item.categories || []).slice(0, 4),
  }));

  return {
    username: mediumUsername,
    profileUrl: `https://medium.com/@${mediumUsername}`,
    articles,
    totalArticles: Math.max(feedItems.length, mediumTotalArticlesFallback),
  };
}

/**
 * Resolve full profile payload from cached live feeds and LinkedIn baseline data.
 */
async function getProfilePayload() {
  const [github, medium] = await Promise.all([
    getCachedOrCompute("github-profile", 1000 * 60 * 30, async () => {
      try {
        return await fetchGithubPayload();
      } catch {
        return {
          profile: {
            username: githubUsername,
            avatarUrl: "",
            followers: 0,
            following: 0,
            publicRepos: 0,
            bio: "",
            profileUrl: `https://github.com/${githubUsername}`,
          },
          repos: [],
        };
      }
    }),
    getCachedOrCompute("medium-profile", 1000 * 60 * 30, async () => {
      try {
        return await fetchMediumPayload();
      } catch {
        return {
          username: mediumUsername,
          profileUrl: `https://medium.com/@${mediumUsername}`,
          articles: [],
          totalArticles: mediumTotalArticlesFallback,
        };
      }
    }),
  ]);

  return {
    ...linkedinProfile,
    github,
    medium,
    updatedAt: new Date().toISOString(),
  };
}

/**
 * Emit a structured request log line without exposing request body content.
 */
function logRequest(req, statusCode, startTime) {
  const latencyMs = Date.now() - startTime;
  console.log(
    JSON.stringify({
      timestamp: new Date().toISOString(),
      requestId: req.requestId,
      method: req.method,
      path: req.originalUrl,
      statusCode,
      latencyMs,
    })
  );
}

/**
 * Select between primary and fast chat models based on prompt complexity.
 */
function selectAnthropicModel(messages, systemPrompt) {
  const promptSize =
    messages.reduce((total, item) => total + String(item.content || "").length, 0) +
    String(systemPrompt || "").length;

  if (promptSize <= chatFastModelThreshold) {
    return anthropicFastModel;
  }

  return anthropicModel;
}

/**
 * Build a bounded message array that keeps recent context while capping char budget.
 */
function buildAnthropicMessages(history, latestMessage) {
  const safeHistory = Array.isArray(history) ? history : [];
  const selectedHistory = [];
  let usedChars = latestMessage.length;

  for (let index = safeHistory.length - 1; index >= 0; index -= 1) {
    const item = safeHistory[index];
    if (!item || (item.role !== "user" && item.role !== "assistant")) {
      continue;
    }

    const sanitizedContent = sanitizeText(item.content || "", 500);
    if (!sanitizedContent) {
      continue;
    }

    if (usedChars + sanitizedContent.length > chatHistoryCharBudget) {
      break;
    }

    usedChars += sanitizedContent.length;
    selectedHistory.unshift({
      role: item.role,
      content: sanitizedContent,
    });
  }

  return [
    ...selectedHistory,
    {
      role: "user",
      content: latestMessage,
    },
  ];
}

/**
 * Send a user message to Anthropic through a server-side authenticated request.
 */
async function sendAnthropicRequest(message, systemPrompt, requestId, history = []) {
  const safePrompt = sanitizeText(message, 1000);
  const safeSystemPrompt = sanitizeText(systemPrompt || defaultChatSystemPrompt, 500);
  const messages = buildAnthropicMessages(history, safePrompt);
  const selectedModel = selectAnthropicModel(messages, safeSystemPrompt);

  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": process.env.ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
      "X-Request-ID": requestId,
    },
    body: JSON.stringify({
      model: selectedModel,
      max_tokens: chatMaxTokens,
      system: safeSystemPrompt,
      messages,
    }),
  });

  if (!response.ok) {
    throw new Error(`Anthropic request failed: ${response.status}`);
  }

  const responseBody = await response.json();
  return {
    content: responseBody?.content?.[0]?.text || "I could not generate a response.",
    model: selectedModel,
  };
}
