// Generated by GitHub Copilot
import crypto from "node:crypto";

import cors from "cors";
import "dotenv/config";
import express from "express";
import rateLimit from "express-rate-limit";
import helmet from "helmet";
import Parser from "rss-parser";
import { z } from "zod";
import { getCachedOrCompute } from "./cache.js";
import linkedinProfile from "./data/linkedinProfile.js";

const app = express();
const feedParser = new Parser();
const port = Number.parseInt(process.env.PORT || "8080", 10);
const anthropicModel = process.env.ANTHROPIC_MODEL || "claude-sonnet-4-20250514";
const corsOrigins = parseCorsOrigins(process.env.CORS_ORIGINS);
const githubUsername = process.env.GITHUB_USERNAME || "Ramdragneel01";
const mediumUsername = process.env.MEDIUM_USERNAME || "RamPrakashD";

const apiLimiter = rateLimit({
  windowMs: 60_000,
  max: Number.parseInt(process.env.API_RATE_LIMIT_PER_MINUTE || "120", 10),
  standardHeaders: true,
  legacyHeaders: false,
  message: {
    error: "Too many requests. Please retry in a minute.",
  },
});

const chatLimiter = rateLimit({
  windowMs: 60_000,
  max: Number.parseInt(process.env.CHAT_RATE_LIMIT_PER_MINUTE || "30", 10),
  standardHeaders: true,
  legacyHeaders: false,
  message: {
    error: "Chat rate limit exceeded. Please retry in a minute.",
  },
});

const contactLimiter = rateLimit({
  windowMs: 3_600_000,
  max: Number.parseInt(process.env.CONTACT_RATE_LIMIT_PER_HOUR || "10", 10),
  standardHeaders: true,
  legacyHeaders: false,
  message: {
    error: "Contact rate limit exceeded. Please retry later.",
  },
});

app.use(
  helmet({
    crossOriginResourcePolicy: { policy: "cross-origin" },
  })
);
app.use(
  cors({
    origin: (origin, callback) => {
      if (isOriginAllowed(origin)) {
        callback(null, true);
        return;
      }
      callback(new Error("Origin not allowed by CORS policy"));
    },
    methods: ["GET", "POST"],
  })
);
app.use(express.json({ limit: "200kb" }));
app.use("/api", apiLimiter);

app.use((req, res, next) => {
  const requestId = req.header("X-Request-ID") || crypto.randomUUID();
  req.requestId = requestId;
  res.setHeader("X-Request-ID", requestId);

  const startTime = Date.now();
  res.on("finish", () => {
    logRequest(req, res.statusCode, startTime);
  });

  next();
});

const chatInputSchema = z
  .object({
    message: z.string().trim().min(1).max(1000).optional(),
    question: z.string().trim().min(1).max(1000).optional(),
    systemPrompt: z.string().trim().max(500).optional(),
  })
  .refine((payload) => Boolean(payload.message || payload.question), {
    message: "Either message or question must be provided.",
  });

const contactInputSchema = z.object({
  name: z.string().trim().min(2).max(120),
  email: z.string().trim().email(),
  message: z.string().trim().min(10).max(4000),
});

app.get("/health", (_req, res) => {
  res.json({
    status: "ok",
    service: "dragon-portfolio-api",
    model: anthropicModel,
    timestamp: new Date().toISOString(),
  });
});

app.get("/api/health", (_req, res) => {
  res.json({
    status: "ok",
    service: "dragon-portfolio-api",
    model: anthropicModel,
    timestamp: new Date().toISOString(),
  });
});

/**
 * Return normalized profile payload merged from static LinkedIn context
 * and live Medium/GitHub profile feeds.
 */
app.get("/api/profile", async (req, res) => {
  try {
    const payload = await getProfilePayload();
    res.json(payload);
  } catch {
    res.status(502).json({
      error: "Could not build profile payload",
      requestId: req.requestId,
    });
  }
});

/**
 * Handle chat prompt requests and proxy to Anthropic with server-side credentials.
 */
app.post("/api/chat", chatLimiter, async (req, res) => {
  const parsedBody = chatInputSchema.safeParse(req.body);
  if (!parsedBody.success) {
    res.status(400).json({
      error: "Invalid chat request payload",
      details: parsedBody.error.flatten(),
      requestId: req.requestId,
    });
    return;
  }

  if (!process.env.ANTHROPIC_API_KEY) {
    res.status(503).json({
      error: "Chat service is not configured",
      requestId: req.requestId,
    });
    return;
  }

  try {
    const prompt = parsedBody.data.message || parsedBody.data.question;
    const content = await sendAnthropicRequest(prompt, parsedBody.data.systemPrompt, req.requestId);
    res.json({
      content,
      reply: content,
      requestId: req.requestId,
    });
  } catch (_error) {
    res.status(502).json({
      error: "Upstream chat provider failure",
      requestId: req.requestId,
    });
  }
});

/**
 * Handle contact form submissions and proxy to EmailJS from the server.
 */
app.post("/api/contact", contactLimiter, async (req, res) => {
  const parsedBody = contactInputSchema.safeParse(req.body);
  if (!parsedBody.success) {
    res.status(400).json({
      error: "Invalid contact request payload",
      details: parsedBody.error.flatten(),
      requestId: req.requestId,
    });
    return;
  }

  const serviceId = process.env.EMAILJS_SERVICE_ID;
  const templateId = process.env.EMAILJS_TEMPLATE_ID;
  const publicKey = process.env.EMAILJS_PUBLIC_KEY;

  if (!serviceId || !templateId || !publicKey) {
    res.status(503).json({
      error: "Contact service is not configured",
      requestId: req.requestId,
    });
    return;
  }

  try {
    const response = await fetch("https://api.emailjs.com/api/v1.0/email/send", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        service_id: serviceId,
        template_id: templateId,
        user_id: publicKey,
        template_params: {
          from_name: sanitizeText(parsedBody.data.name, 120),
          from_email: sanitizeText(parsedBody.data.email, 150),
          message: sanitizeText(parsedBody.data.message, 2000),
        },
      }),
    });

    if (!response.ok) {
      throw new Error(`EmailJS request failed: ${response.status}`);
    }

    res.json({
      status: "sent",
      requestId: req.requestId,
    });
  } catch {
    res.status(502).json({
      error: "Could not deliver message at this time",
      requestId: req.requestId,
    });
  }
});

app.use((error, req, res, next) => {
  if (error?.message === "Origin not allowed by CORS policy") {
    res.status(403).json({
      error: "Origin is not allowed",
      requestId: req.requestId,
    });
    return;
  }

  next(error);
});

app.listen(port, () => {
  console.log(`[dragon-portfolio-api] listening on port ${port}`);
});

/**
 * Parse a comma-separated CORS origin string into an allowlist set.
 */
function parseCorsOrigins(originInput) {
  return new Set(
    (originInput || "http://127.0.0.1:5173,http://localhost:5173")
      .split(",")
      .map((origin) => origin.trim())
      .filter(Boolean)
  );
}

/**
 * Check if a request origin is allowed by explicit list or Vercel previews.
 */
function isOriginAllowed(origin) {
  if (!origin) {
    return true;
  }

  if (corsOrigins.has(origin)) {
    return true;
  }

  return origin.endsWith(".vercel.app");
}

/**
 * Normalize user text inputs by reducing whitespace and max length.
 */
function sanitizeText(value, maxLength) {
  return String(value).replace(/\s+/g, " ").trim().slice(0, maxLength);
}

/**
 * Build GitHub API headers with optional token support.
 */
function getGithubHeaders() {
  const headers = {
    Accept: "application/vnd.github+json",
    "User-Agent": "dragon-portfolio-service",
  };

  if (process.env.GITHUB_TOKEN) {
    headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;
  }

  return headers;
}

/**
 * Fetch profile and repository metadata from GitHub.
 */
async function fetchGithubPayload() {
  const [profileResponse, repositoriesResponse] = await Promise.all([
    fetch(`https://api.github.com/users/${githubUsername}`, {
      headers: getGithubHeaders(),
    }),
    fetch(`https://api.github.com/users/${githubUsername}/repos?sort=updated&per_page=8&type=owner`, {
      headers: getGithubHeaders(),
    }),
  ]);

  if (!profileResponse.ok || !repositoriesResponse.ok) {
    throw new Error("GitHub profile request failed");
  }

  const profile = await profileResponse.json();
  const repositories = await repositoriesResponse.json();

  return {
    profile: {
      username: profile.login,
      avatarUrl: profile.avatar_url || "",
      followers: profile.followers || 0,
      following: profile.following || 0,
      publicRepos: profile.public_repos || 0,
      bio: profile.bio || "",
      profileUrl: profile.html_url || `https://github.com/${githubUsername}`,
    },
    repos: Array.isArray(repositories)
      ? repositories.map((repo) => ({
          id: String(repo.id),
          title: repo.name,
          description: repo.description || "No description provided yet.",
          github: repo.html_url,
          tags: [repo.language, ...(repo.topics || [])].filter(Boolean).slice(0, 4),
          stars: repo.stargazers_count || 0,
          forks: repo.forks_count || 0,
          updatedAt: repo.updated_at || "",
        }))
      : [],
  };
}

/**
 * Fetch and normalize latest Medium articles through RSS feed.
 */
async function fetchMediumPayload() {
  const feed = await feedParser.parseURL(`https://medium.com/feed/@${mediumUsername}`);
  const articles = (feed.items || []).slice(0, 6).map((item, index) => ({
    id: item.guid || item.link || `${item.title || "article"}-${index}`,
    title: item.title || "Untitled article",
    link: item.link || `https://medium.com/@${mediumUsername}`,
    excerpt: sanitizeText(item.contentSnippet || item.content || "", 200),
    publishedAt: item.isoDate || item.pubDate || "",
    categories: (item.categories || []).slice(0, 4),
  }));

  return {
    username: mediumUsername,
    profileUrl: `https://medium.com/@${mediumUsername}`,
    articles,
  };
}

/**
 * Resolve full profile payload from cached live feeds and LinkedIn baseline data.
 */
async function getProfilePayload() {
  const [github, medium] = await Promise.all([
    getCachedOrCompute("github-profile", 1000 * 60 * 30, async () => {
      try {
        return await fetchGithubPayload();
      } catch {
        return {
          profile: {
            username: githubUsername,
            avatarUrl: "",
            followers: 0,
            following: 0,
            publicRepos: 0,
            bio: "",
            profileUrl: `https://github.com/${githubUsername}`,
          },
          repos: [],
        };
      }
    }),
    getCachedOrCompute("medium-profile", 1000 * 60 * 30, async () => {
      try {
        return await fetchMediumPayload();
      } catch {
        return {
          username: mediumUsername,
          profileUrl: `https://medium.com/@${mediumUsername}`,
          articles: [],
        };
      }
    }),
  ]);

  return {
    ...linkedinProfile,
    github,
    medium,
    updatedAt: new Date().toISOString(),
  };
}

/**
 * Emit a structured request log line without exposing request body content.
 */
function logRequest(req, statusCode, startTime) {
  const latencyMs = Date.now() - startTime;
  console.log(
    JSON.stringify({
      timestamp: new Date().toISOString(),
      requestId: req.requestId,
      method: req.method,
      path: req.originalUrl,
      statusCode,
      latencyMs,
    })
  );
}

/**
 * Send a user message to Anthropic through a server-side authenticated request.
 */
async function sendAnthropicRequest(message, systemPrompt, requestId) {
  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": process.env.ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
      "X-Request-ID": requestId,
    },
    body: JSON.stringify({
      model: anthropicModel,
      max_tokens: 400,
      system:
        systemPrompt ||
        "You are a concise assistant for Ram's portfolio. Prioritize factual project summaries and practical impact.",
      messages: [{ role: "user", content: sanitizeText(message, 1000) }],
    }),
  });

  if (!response.ok) {
    throw new Error(`Anthropic request failed: ${response.status}`);
  }

  const responseBody = await response.json();
  return responseBody?.content?.[0]?.text || "I could not generate a response.";
}
