// Generated by GitHub Copilot
import { motion } from "framer-motion";

/**
 * Render the dedicated about page narrative.
 *
 * @returns {JSX.Element} About page section.
 */
function AboutPage() {
    return (
        <section className="py-16" id="about-page">
            <motion.div
                className="glass-card-strong mx-auto max-w-4xl rounded-3xl p-6 md:p-8"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, ease: "easeOut" }}
            >
                <h1 className="text-2xl font-semibold tracking-tight text-[var(--text-primary)] md:text-3xl">
                    About Me
                </h1>

                <div className="mt-4 space-y-4 text-sm leading-relaxed text-[var(--text-secondary)] md:text-base">
                    <p>
                        Most people online know me as dragon. I am 24, and I build AI and ML products in R&D at
                        Accenture India. I like leading from the front, staying close to the people I work with, and
                        shipping things that solve real problems.
                    </p>
                    <p>
                        My journey started with a BE in Computer Science with a 9.17 CGPA, then early R&D roles at
                        Infyleads and IVIS International before Accenture. At Accenture, I built config-driven UI suites
                        and AI observability dashboards in React and Next.js, and helped deliver an LLM chatbot with a
                        Python backend. I earned the GCP Professional ML Engineer certification and a Tech Expert badge
                        while keeping my work practical and product-focused.
                    </p>
                    <p>
                        Outside work, anime, manga, and Japanese culture keep my creative side alive, and a spiritual
                        mindset keeps me intentional without being religious. I communicate directly, care about impact,
                        and keep learning fast & am focused on ML and data science, and building toward reliable systems 
                        teams can trust in production.
                    </p>
                </div>
            </motion.div>
        </section>
    );
}

export default AboutPage;
