// Generated by GitHub Copilot
import { Link } from "react-router-dom";
import Contact from "../components/Contact";

/**
 * Render the dedicated contact page.
 *
 * @param {{config: Record<string, any>, apiBaseUrl: string}} props Component props.
 * @returns {JSX.Element} Contact page section.
 */
function ContactPage({ config, apiBaseUrl }) {
    return (
        <>
            <div className="pt-4">
                <Link to="/" className="glass-chip inline-flex rounded-full px-4 py-2 text-xs font-semibold uppercase tracking-[0.14em] text-[var(--text-primary)]">
                    Back to Home
                </Link>
            </div>
            <Contact config={config} apiBaseUrl={apiBaseUrl} />
        </>
    );
}

export default ContactPage;
