// Generated by GitHub Copilot
import { Link } from "react-router-dom";
import Insights from "../components/Insights";

/**
 * Render the dedicated Medium insights page.
 *
 * @param {{profile: Record<string, any>, loading?: boolean}} props Component props.
 * @returns {JSX.Element} Insights page section.
 */
function InsightsPage({ profile, loading = false }) {
    return (
        <>
            <div className="pt-4">
                <Link to="/" className="glass-chip inline-flex rounded-full px-4 py-2 text-xs font-semibold uppercase tracking-[0.14em] text-[var(--text-primary)]">
                    Back to Home
                </Link>
            </div>
            <Insights profile={profile} loading={loading} />
        </>
    );
}

export default InsightsPage;
