// Generated by GitHub Copilot
import { Link } from "react-router-dom";
import Projects from "../components/Projects";

/**
 * Render the dedicated projects page.
 *
 * @param {{projects: Array<Record<string, any>>, config: Record<string, any>, loading?: boolean}} props Component props.
 * @returns {JSX.Element} Projects page section.
 */
function ProjectsPage({ projects, config, loading = false }) {
    return (
        <section className="glass-card mt-4 rounded-3xl px-4 pb-6 md:px-8" id="projects-page">
            <div className="pt-4">
                <Link to="/" className="glass-chip inline-flex rounded-full px-4 py-2 text-xs font-semibold uppercase tracking-[0.14em] text-[var(--text-primary)]">
                    Back to Home
                </Link>
            </div>
            <Projects projects={projects} config={config} loading={loading} />
        </section>
    );
}

export default ProjectsPage;
