// Generated by GitHub Copilot
export const siteConfig = {
  identity: {
    name: "Ram Prakash (Venkat Sampath Siva) Dhulipudi | dragon",
    heading: "ML Engineer | Packaged App Development @ Accenture | GCP Professional ML Engineer",
    summary:
      "I build production AI systems and scalable frontend platforms with a strong focus on trust, observability, and shipping velocity.",
    roles: ["Data Scientist", "ML Engineer", "React Architect", "GenAI Builder"],
  },
  sections: [
    { id: "hero", component: "Hero", enabled: true },
    { id: "projects", component: "Projects", enabled: true },
    { id: "about", component: "About", enabled: true },
    { id: "insights", component: "Insights", enabled: true },
    { id: "contact", component: "Contact", enabled: true },
  ],
  projects: {
    title: "Projects",
    subtitle:
      "Curated STAR case studies plus GitHub engineering projects in one unified portfolio.",
  },
  about: {
    title: "About",
    summary:
      "I design trustworthy AI and ML products with production observability, resilient architecture, and measurable business outcomes.",
    skills: [
      { name: "Python", level: 95 },
      { name: "Machine Learning", level: 94 },
      { name: "Artificial Intelligence", level: 93 },
      { name: "React", level: 91 },
      { name: "Micro-Frontend Architecture", level: 89 },
    ],
  },
  contact: {
    title: "Contact",
    submitButtonLabel: "Send Message",
    placeholders: {
      name: "Your name",
      email: "Your email",
      message: "Your message",
    },
    statuses: {
      sending: "Sending...",
      success: "Message sent successfully.",
      failure: "Could not send message right now.",
    },
  },
  chat: {
    enabled: true,
    title: "Dragon Assistant",
    welcomeMessage:
      "Are you here for hiring or just browsing? Select a mode first so I can tailor my responses.",
    placeholder: "Ask a specific question about Ram's portfolio...",
    systemPrompt:
      "You are a concise assistant for Ram Prakash Dhulipudi's portfolio. Prioritize factual project summaries and practical impact.",
  },
  api: {
    baseUrl: import.meta.env.VITE_API_BASE_URL || "/api",
  },
};
