// Generated by GitHub Copilot
export const siteConfig = {
  identity: {
    name: "Ram Prakash (Venkat Sampath Siva) Dhulipudi",
    heading: "ML Engineer | Packaged App Development @ Accenture",
    summary:
      "I design production-ready AI systems with observability, scalability, and measurable user impact.",
    roles: ["ML Engineer", "Packaged App Developer", "Data Scientist", "GenAI Builder"],
  },
  sections: [
    { id: "hero", component: "Hero", enabled: true },
    { id: "projects", component: "Projects", enabled: true },
    { id: "about", component: "About", enabled: true },
    { id: "insights", component: "Insights", enabled: true },
    { id: "contact", component: "Contact", enabled: true },
  ],
  projects: {
    title: "Projects",
    subtitle:
      "Curated STAR case studies plus GitHub engineering projects in one unified portfolio.",
  },
  about: {
    title: "About",
    summary:
      "I build ML products that are measurable in production with strong focus on reliability, model drift awareness, and practical user impact.",
    skills: [
      { name: "Python", level: 92 },
      { name: "React", level: 84 },
      { name: "MLOps", level: 88 },
      { name: "AWS", level: 80 },
      { name: "LLMs", level: 90 },
    ],
  },
  contact: {
    title: "Contact",
    submitButtonLabel: "Send Message",
    placeholders: {
      name: "Your name",
      email: "Your email",
      message: "Your message",
    },
    statuses: {
      sending: "Sending...",
      success: "Message sent successfully.",
      failure: "Could not send message right now.",
    },
  },
  chat: {
    enabled: true,
    title: "Dragon Assistant",
    welcomeMessage:
      "Are you here for hiring or just browsing? Select a mode first so I can tailor my responses.",
    placeholder: "Ask a specific question about Ram's portfolio...",
    systemPrompt:
      "You are a concise assistant for Ram Prakash Dhulipudi's portfolio. Prioritize factual project summaries and practical impact.",
  },
  api: {
    baseUrl: import.meta.env.VITE_API_BASE_URL || "/api",
  },
};
