// Generated by GitHub Copilot
import { motion } from "framer-motion";

const SKILLS = [
  { name: "Python", level: 92 },
  { name: "React", level: 84 },
  { name: "MLOps", level: 88 },
  { name: "AWS", level: 80 },
  { name: "LLMs", level: 90 },
];

/**
 * Render profile background with skill bars, language proficiency, and experience highlights.
 *
 * @param {{config: Record<string, any>, profile: Record<string, any>}} props Component props.
 * @returns {JSX.Element} About section.
 */
function About({ config, profile }) {
  const skills = profile?.topSkills?.length ? profile.topSkills : config?.skills?.length ? config.skills : SKILLS;
  const languages = profile?.languages || [];
  const experience = profile?.experience || [];
  const summary = profile?.identity?.summary || config?.summary;

  return (
    <section className="py-16" id="about">
      <motion.h2
        className="text-3xl font-bold"
        initial={{ opacity: 0, y: 16 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ amount: 0.3, once: true }}
        transition={{ duration: 0.55, ease: "easeOut" }}
      >
        {config?.title}
      </motion.h2>
      <motion.p
        className="mt-2 max-w-3xl text-dragon-sand/80"
        initial={{ opacity: 0, y: 16 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ amount: 0.3, once: true }}
        transition={{ duration: 0.55, delay: 0.1, ease: "easeOut" }}
      >
        {summary}
      </motion.p>

      <div className="mt-8 grid gap-6 lg:grid-cols-[1.2fr,0.8fr]">
        <motion.div
          className="space-y-4 rounded-3xl border border-dragon-red/25 bg-dragon-navySoft/60 p-6"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ amount: 0.2, once: true }}
          transition={{ duration: 0.6, ease: "easeOut" }}
        >
          <h3 className="text-xl font-semibold">Top Skills</h3>
          {skills.map((skill) => (
            <div key={skill.name}>
              <div className="mb-1 flex items-center justify-between text-sm">
                <span>{skill.name}</span>
                <span>{skill.level}%</span>
              </div>
              <div className="h-3 overflow-hidden rounded bg-dragon-navySoft">
                <div
                  className="h-full rounded bg-dragon-red transition-all duration-700 ease-out"
                  style={{ width: `${skill.level}%` }}
                  aria-label={`${skill.name} proficiency ${skill.level} percent`}
                />
              </div>
            </div>
          ))}
        </motion.div>

        <motion.aside
          className="rounded-3xl border border-dragon-red/25 bg-dragon-navySoft/60 p-6"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ amount: 0.2, once: true }}
          transition={{ duration: 0.6, delay: 0.1, ease: "easeOut" }}
        >
          <h3 className="text-xl font-semibold">Languages</h3>
          <ul className="mt-4 space-y-2">
            {languages.map((language) => (
              <li key={language.name} className="rounded-xl border border-dragon-red/20 bg-dragon-navy/70 px-3 py-2 text-sm">
                <span className="font-semibold">{language.name}</span>
                <span className="ml-2 text-dragon-sand/70">{language.proficiency}</span>
              </li>
            ))}
          </ul>
        </motion.aside>
      </div>

      <motion.div
        className="mt-6 rounded-3xl border border-dragon-red/25 bg-dragon-navySoft/60 p-6"
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ amount: 0.2, once: true }}
        transition={{ duration: 0.6, delay: 0.15, ease: "easeOut" }}
      >
        <h3 className="text-xl font-semibold">Experience Highlights</h3>
        <ol className="mt-4 space-y-4">
          {experience.slice(0, 4).map((role) => (
            <li key={`${role.company}-${role.role}`} className="rounded-2xl border border-dragon-red/20 bg-dragon-navy/70 p-4">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <p className="text-base font-semibold">{role.role}</p>
                <p className="text-xs uppercase tracking-[0.15em] text-dragon-sand/65">{role.period}</p>
              </div>
              <p className="mt-1 text-sm text-dragon-redGlow">{role.company}</p>
              <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-dragon-sand/80">
                {(role.highlights || []).slice(0, 2).map((highlight) => (
                  <li key={highlight}>{highlight}</li>
                ))}
              </ul>
            </li>
          ))}
        </ol>
      </motion.div>
    </section>
  );
}

export default About;
