// Generated by GitHub Copilot
const SKILLS = [
  { name: "Python", level: 92 },
  { name: "React", level: 84 },
  { name: "MLOps", level: 88 },
  { name: "AWS", level: 80 },
  { name: "LLMs", level: 90 },
];

function About() {
  return (
    <section className="py-16" id="about">
      <h2 className="text-3xl font-bold">About</h2>
      <p className="mt-2 max-w-3xl text-dragon-sand/80">
        I design ML products that are measurable in production, with strong attention to reliability,
        drift detection, and user-first interfaces.
      </p>
      <div className="mt-8 space-y-4">
        {SKILLS.map((skill) => (
          <div key={skill.name}>
            <div className="mb-1 flex items-center justify-between text-sm">
              <span>{skill.name}</span>
              <span>{skill.level}%</span>
            </div>
            <div className="h-3 overflow-hidden rounded bg-dragon-navySoft">
              <div
                className="h-full rounded bg-dragon-red transition-all duration-700 ease-out"
                style={{ width: `${skill.level}%` }}
                aria-label={`${skill.name} proficiency ${skill.level} percent`}
              />
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

export default About;
