// Generated by GitHub Copilot
import { useMemo, useState } from "react";

const MODEL = "claude-sonnet-4-20250514";

function Chatbot() {
  const [open, setOpen] = useState(false);
  const [question, setQuestion] = useState("");
  const [loading, setLoading] = useState(false);
  const [messages, setMessages] = useState([
    {
      role: "assistant",
      content: "Ask me about Ram's projects, skills, or architecture decisions.",
    },
  ]);

  const apiKey = useMemo(() => import.meta.env.VITE_ANTHROPIC_API_KEY || "", []);

  /**
   * Send a user query to Anthropic and append the assistant response.
   * Security note: production usage should proxy this call through a backend.
   */
  async function sendMessage() {
    if (!question.trim() || loading) {
      return;
    }

    const userMessage = { role: "user", content: question.trim() };
    setMessages((prev) => [...prev, userMessage]);
    setQuestion("");
    setLoading(true);

    try {
      const response = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": apiKey,
          "anthropic-version": "2023-06-01",
        },
        body: JSON.stringify({
          model: MODEL,
          max_tokens: 400,
          system:
            "You are a concise assistant for Ram's portfolio. Prioritize factual project summaries and practical impact.",
          messages: [{ role: "user", content: userMessage.content }],
        }),
      });

      if (!response.ok) {
        throw new Error(`Anthropic request failed: ${response.status}`);
      }

      const payload = await response.json();
      const content = payload?.content?.[0]?.text || "I could not generate a response.";
      setMessages((prev) => [...prev, { role: "assistant", content }]);
    } catch (error) {
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          content: "Chat is temporarily unavailable. Please try again.",
        },
      ]);
      console.error(error);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="fixed bottom-4 right-4 z-50">
      {open && (
        <div className="mb-3 w-[320px] rounded-2xl border border-dragon-red/35 bg-dragon-navySoft/95 p-4 shadow-glow md:w-[360px]">
          <h3 className="mb-3 text-sm font-bold text-dragon-redGlow">Dragon Assistant</h3>
          <div className="mb-3 max-h-64 space-y-2 overflow-y-auto pr-1">
            {messages.map((message, index) => (
              <div
                key={`${message.role}-${index}`}
                className={`rounded-lg p-2 text-sm ${
                  message.role === "user" ? "bg-dragon-red/20" : "bg-dragon-navy"
                }`}
              >
                {message.content}
              </div>
            ))}
          </div>
          <div className="flex gap-2">
            <input
              className="w-full rounded-lg border border-dragon-red/30 bg-dragon-navy px-3 py-2 text-sm outline-none focus:border-dragon-redGlow"
              value={question}
              onChange={(event) => setQuestion(event.target.value)}
              onKeyDown={(event) => {
                if (event.key === "Enter") {
                  sendMessage();
                }
              }}
              placeholder="Ask about projects..."
              aria-label="Chat question input"
            />
            <button
              type="button"
              onClick={sendMessage}
              disabled={loading}
              className="rounded-lg bg-dragon-red px-3 py-2 text-sm font-semibold disabled:opacity-60"
            >
              Send
            </button>
          </div>
        </div>
      )}
      <button
        type="button"
        onClick={() => setOpen((prev) => !prev)}
        className="rounded-full bg-dragon-red px-5 py-3 text-sm font-bold text-white shadow-glow"
      >
        {open ? "Close Chat" : "Open Chat"}
      </button>
    </div>
  );
}

export default Chatbot;
