// Generated by GitHub Copilot
import { useState } from "react";

function Contact() {
  const [status, setStatus] = useState("");
  const [form, setForm] = useState({ name: "", email: "", message: "" });

  /**
   * Submit the contact form through EmailJS REST endpoint.
   */
  async function handleSubmit(event) {
    event.preventDefault();
    setStatus("Sending...");

    try {
      const response = await fetch("https://api.emailjs.com/api/v1.0/email/send", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          service_id: import.meta.env.VITE_EMAILJS_SERVICE_ID,
          template_id: import.meta.env.VITE_EMAILJS_TEMPLATE_ID,
          user_id: import.meta.env.VITE_EMAILJS_KEY,
          template_params: {
            from_name: form.name,
            from_email: form.email,
            message: form.message,
          },
        }),
      });

      if (!response.ok) {
        throw new Error(`EmailJS request failed: ${response.status}`);
      }

      setStatus("Message sent successfully.");
      setForm({ name: "", email: "", message: "" });
    } catch (error) {
      setStatus("Could not send message right now.");
      console.error(error);
    }
  }

  return (
    <section className="py-16" id="contact">
      <h2 className="text-3xl font-bold">Contact</h2>
      <form className="mt-6 max-w-2xl space-y-4" onSubmit={handleSubmit}>
        <input
          className="w-full rounded-lg border border-dragon-red/30 bg-dragon-navySoft px-4 py-3 outline-none focus:border-dragon-redGlow"
          type="text"
          value={form.name}
          onChange={(event) => setForm((prev) => ({ ...prev, name: event.target.value }))}
          placeholder="Your name"
          required
        />
        <input
          className="w-full rounded-lg border border-dragon-red/30 bg-dragon-navySoft px-4 py-3 outline-none focus:border-dragon-redGlow"
          type="email"
          value={form.email}
          onChange={(event) => setForm((prev) => ({ ...prev, email: event.target.value }))}
          placeholder="Your email"
          required
        />
        <textarea
          className="min-h-32 w-full rounded-lg border border-dragon-red/30 bg-dragon-navySoft px-4 py-3 outline-none focus:border-dragon-redGlow"
          value={form.message}
          onChange={(event) => setForm((prev) => ({ ...prev, message: event.target.value }))}
          placeholder="Your message"
          required
        />
        <button
          className="rounded-lg bg-dragon-red px-5 py-3 font-semibold text-white transition hover:bg-dragon-redGlow"
          type="submit"
        >
          Send Message
        </button>
        <p className="text-sm text-dragon-sand/80" aria-live="polite">
          {status}
        </p>
      </form>
    </section>
  );
}

export default Contact;
