// Generated by GitHub Copilot
import { useEffect, useRef, useState } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import { Float, OrbitControls, Stars } from "@react-three/drei";
import { motion, useReducedMotion } from "framer-motion";

const DEFAULT_ROLES = ["Data Scientist", "ML Engineer", "GenAI Builder"];

/**
 * Render a rotating geometric cluster for the hero 3D scene.
 *
 * @returns {JSX.Element} Three.js mesh group.
 */
function HeroGeometry() {
  const meshRef = useRef(null);

  useFrame((state, delta) => {
    if (!meshRef.current) {
      return;
    }

    meshRef.current.rotation.x += delta * 0.2;
    meshRef.current.rotation.y += delta * 0.35;
    meshRef.current.position.y = Math.sin(state.clock.elapsedTime * 0.8) * 0.2;
  });

  return (
    <group>
      <Float speed={1.2} rotationIntensity={1.2} floatIntensity={1.4}>
        <mesh ref={meshRef}>
          <torusKnotGeometry args={[1.1, 0.26, 120, 22]} />
          <meshStandardMaterial color="#ff6b42" roughness={0.2} metalness={0.7} />
        </mesh>
      </Float>

      <Float speed={0.8} rotationIntensity={0.7} floatIntensity={1.2}>
        <mesh position={[-2.2, -1.3, -0.3]}>
          <icosahedronGeometry args={[0.52, 1]} />
          <meshStandardMaterial color="#ffd166" roughness={0.4} metalness={0.5} />
        </mesh>
      </Float>

      <Float speed={0.7} rotationIntensity={0.7} floatIntensity={1.2}>
        <mesh position={[2.4, 1.4, -0.2]}>
          <octahedronGeometry args={[0.45, 0]} />
          <meshStandardMaterial color="#68d8d6" roughness={0.25} metalness={0.5} />
        </mesh>
      </Float>
    </group>
  );
}

/**
 * Render the 3D hero canvas scene.
 *
 * @returns {JSX.Element} Canvas block.
 */
function HeroScene() {
  return (
    <Canvas camera={{ position: [0, 0, 4.5], fov: 52 }}>
      <ambientLight intensity={0.8} />
      <directionalLight intensity={1.1} position={[3, 3, 4]} />
      <pointLight intensity={0.65} position={[-2, -1, 2]} color="#ff6b42" />
      <Stars radius={16} depth={35} count={700} factor={3} saturation={0.4} fade speed={0.7} />
      <HeroGeometry />
      <OrbitControls enablePan={false} enableZoom={false} autoRotate autoRotateSpeed={0.8} />
    </Canvas>
  );
}

/**
 * Render the portfolio hero section with 3D scene and typed role animation.
 *
 * @param {{config: Record<string, any>, profile: Record<string, any>, loading: boolean}} props Component props.
 * @returns {JSX.Element} Hero section markup.
 */
function Hero({ config, profile, loading }) {
  const reduceMotion = useReducedMotion();
  const roles = config?.roles?.length ? config.roles : DEFAULT_ROLES;
  const [roleIndex, setRoleIndex] = useState(0);
  const [typed, setTyped] = useState("");

  useEffect(() => {
    const full = roles[roleIndex % roles.length];
    let charIndex = 0;

    const interval = setInterval(() => {
      charIndex += 1;
      setTyped(full.slice(0, charIndex));
      if (charIndex >= full.length) {
        clearInterval(interval);
        setTimeout(() => {
          setRoleIndex((prev) => (prev + 1) % roles.length);
          setTyped("");
        }, 1200);
      }
    }, 70);

    return () => clearInterval(interval);
  }, [roleIndex, roles]);

  const displayName = profile?.identity?.name || config?.name;
  const displayHeadline = profile?.identity?.headline || config?.heading;
  const displaySummary = profile?.identity?.summary || config?.summary;
  const displayLocation = profile?.identity?.location || "Hyderabad, India";

  return (
    <section className="relative overflow-hidden py-20 md:py-24" id="home">
      <div className="absolute -left-16 top-10 h-72 w-72 rounded-full bg-[#ff6b42]/25 blur-3xl" />
      <div className="absolute -right-20 bottom-8 h-80 w-80 rounded-full bg-[#68d8d6]/20 blur-3xl" />

      <div className="grid gap-8 lg:grid-cols-[1.1fr,0.9fr] lg:items-center">
        <motion.div
          initial={{ opacity: 0, y: 26 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, ease: "easeOut" }}
          className="relative rounded-3xl border border-dragon-red/35 bg-dragon-navySoft/75 p-8 shadow-glow md:p-12"
        >
          <p className="text-sm uppercase tracking-[0.25em] text-dragon-redGlow">{displayName}</p>
          <h1 className="mt-3 font-display text-5xl leading-none md:text-7xl">{displayHeadline}</h1>
          <p className="mt-4 text-sm uppercase tracking-[0.2em] text-dragon-sand/70">{displayLocation}</p>
          <p className="mt-5 text-lg text-dragon-sand/90 md:text-xl">{displaySummary}</p>

          <div className="mt-6 h-9 text-lg text-dragon-redGlow md:text-xl" aria-live="polite">
            {typed}
            <span className="ml-1 inline-block h-6 w-[2px] animate-pulse bg-dragon-redGlow align-middle" />
          </div>

          <div className="mt-8 flex flex-wrap gap-3">
            <a
              href="#projects"
              className="rounded-full bg-dragon-red px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-dragon-redGlow"
            >
              Explore Projects
            </a>
            <a
              href={profile?.contact?.linkedin || "https://www.linkedin.com/in/ramprakashdhulipudi/"}
              target="_blank"
              rel="noreferrer"
              className="rounded-full border border-dragon-red/35 px-5 py-2.5 text-sm font-semibold text-dragon-sand transition hover:border-dragon-redGlow hover:text-dragon-redGlow"
            >
              LinkedIn Profile
            </a>
          </div>

          {loading ? (
            <p className="mt-4 text-sm text-dragon-sand/65">Syncing live profile context...</p>
          ) : null}
        </motion.div>

        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ amount: 0.25, once: true }}
          transition={{ duration: 0.8, ease: "easeOut" }}
          className="h-[320px] overflow-hidden rounded-3xl border border-dragon-red/25 bg-[#050d16]/70 shadow-[0_20px_70px_rgba(255,107,66,0.22)] md:h-[420px]"
        >
          {reduceMotion ? (
            <div className="flex h-full items-center justify-center bg-[radial-gradient(circle_at_35%_35%,rgba(255,107,66,0.35),transparent_45%),radial-gradient(circle_at_70%_65%,rgba(104,216,214,0.35),transparent_42%)]">
              <p className="rounded-full border border-dragon-red/40 bg-dragon-navy/70 px-4 py-2 text-sm text-dragon-sand">
                3D mode reduced for accessibility preferences.
              </p>
            </div>
          ) : (
            <HeroScene />
          )}
        </motion.div>
      </div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ amount: 0.2, once: true }}
        transition={{ duration: 0.6, delay: 0.1, ease: "easeOut" }}
        className="mt-10 grid gap-4 rounded-2xl border border-dragon-red/20 bg-dragon-navySoft/55 p-4 md:grid-cols-3"
      >
        <div>
          <p className="text-xs uppercase tracking-[0.18em] text-dragon-sand/60">GitHub</p>
          <p className="mt-1 text-2xl font-semibold text-dragon-redGlow">
            {profile?.github?.profile?.publicRepos ?? 0}
          </p>
          <p className="text-sm text-dragon-sand/70">Public repositories</p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-[0.18em] text-dragon-sand/60">Followers</p>
          <p className="mt-1 text-2xl font-semibold text-dragon-redGlow">
            {profile?.github?.profile?.followers ?? 0}
          </p>
          <p className="text-sm text-dragon-sand/70">Developer network on GitHub</p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-[0.18em] text-dragon-sand/60">Medium</p>
          <p className="mt-1 text-2xl font-semibold text-dragon-redGlow">
            {profile?.medium?.articles?.length ?? 0}
          </p>
          <p className="text-sm text-dragon-sand/70">Recent published articles</p>
        </div>
      </motion.div>
    </section>
  );
}

export default Hero;
