// Generated by GitHub Copilot
import { useEffect, useState } from "react";

const ROLES = ["Data Scientist", "ML Engineer", "GenAI Builder"];

function Hero() {
  const [roleIndex, setRoleIndex] = useState(0);
  const [typed, setTyped] = useState("");

  useEffect(() => {
    const full = ROLES[roleIndex];
    let charIndex = 0;

    const interval = setInterval(() => {
      charIndex += 1;
      setTyped(full.slice(0, charIndex));
      if (charIndex >= full.length) {
        clearInterval(interval);
        setTimeout(() => {
          setRoleIndex((prev) => (prev + 1) % ROLES.length);
          setTyped("");
        }, 1200);
      }
    }, 70);

    return () => clearInterval(interval);
  }, [roleIndex]);

  return (
    <section className="relative overflow-hidden py-20 md:py-28" id="home">
      <div className="absolute -left-20 top-10 h-72 w-72 rounded-full bg-dragon-red/20 blur-3xl" />
      <div className="absolute -right-24 bottom-0 h-80 w-80 rounded-full bg-dragon-redGlow/15 blur-3xl" />
      <div className="relative animate-floatIn rounded-3xl border border-dragon-red/30 bg-dragon-navySoft/70 p-8 shadow-glow md:p-12">
        <p className="text-sm uppercase tracking-[0.25em] text-dragon-redGlow">Ram Prakash</p>
        <h1 className="mt-3 text-4xl font-bold leading-tight md:text-6xl">Dragon Portfolio</h1>
        <p className="mt-5 text-xl text-dragon-sand/90 md:text-2xl">
          I build production ML systems with explainability, observability, and real user impact.
        </p>
        <div className="mt-6 h-9 text-lg text-dragon-redGlow md:text-xl" aria-live="polite">
          {typed}
          <span className="ml-1 inline-block h-6 w-[2px] animate-pulse bg-dragon-redGlow align-middle" />
        </div>
      </div>
    </section>
  );
}

export default Hero;
