// Generated by GitHub Copilot
import { motion } from "framer-motion";

/**
 * Render Medium highlights and certification tags as a scroll-revealed insight block.
 *
 * @param {{profile: Record<string, any>}} props Component props.
 * @returns {JSX.Element} Insights section markup.
 */
function Insights({ profile }) {
  const mediumArticles = profile?.medium?.articles || [];
  const certifications = profile?.certifications || [];
  const mediumProfileUrl = profile?.medium?.profileUrl || "https://medium.com/@RamPrakashD";

  return (
    <section className="py-16" id="insights">
      <motion.div
        initial={{ opacity: 0, y: 24 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ amount: 0.2, once: true }}
        transition={{ duration: 0.6, ease: "easeOut" }}
      >
        <h2 className="text-3xl font-bold">Medium Insights and Certifications</h2>
        <p className="mt-2 max-w-3xl text-dragon-sand/80">
          Live writing from Medium and credential signals that reflect ongoing experimentation in
          applied AI, MLOps, and product engineering.
        </p>
      </motion.div>

      <div className="mt-8 grid gap-6 lg:grid-cols-[2fr,1fr]">
        <motion.div
          className="rounded-3xl border border-dragon-red/20 bg-dragon-navySoft/70 p-6"
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ amount: 0.2, once: true }}
          transition={{ delay: 0.1, duration: 0.6, ease: "easeOut" }}
        >
          <div className="mb-4 flex items-center justify-between gap-3">
            <h3 className="text-xl font-semibold">Latest Medium Articles</h3>
            <a
              href={mediumProfileUrl}
              target="_blank"
              rel="noreferrer"
              className="text-sm font-semibold text-dragon-redGlow hover:underline"
            >
              Visit profile
            </a>
          </div>

          {mediumArticles.length ? (
            <ul className="space-y-3">
              {mediumArticles.slice(0, 5).map((article) => (
                <li
                  key={article.id}
                  className="rounded-2xl border border-dragon-red/20 bg-dragon-navy/70 p-4"
                >
                  <a
                    href={article.link}
                    target="_blank"
                    rel="noreferrer"
                    className="text-base font-semibold text-dragon-sand hover:text-dragon-redGlow"
                  >
                    {article.title}
                  </a>
                  <p className="mt-2 text-sm text-dragon-sand/75">{article.excerpt}</p>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-dragon-sand/70">
              Medium feed is syncing. The profile link is available while we refresh articles.
            </p>
          )}
        </motion.div>

        <motion.aside
          className="rounded-3xl border border-dragon-red/20 bg-dragon-navySoft/70 p-6"
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ amount: 0.2, once: true }}
          transition={{ delay: 0.2, duration: 0.6, ease: "easeOut" }}
        >
          <h3 className="text-xl font-semibold">Certifications</h3>
          <ul className="mt-4 space-y-2">
            {certifications.map((certification) => (
              <li
                key={certification}
                className="rounded-xl border border-dragon-red/20 bg-dragon-navy/70 px-3 py-2 text-sm"
              >
                {certification}
              </li>
            ))}
          </ul>
        </motion.aside>
      </div>
    </section>
  );
}

export default Insights;
