// Generated by GitHub Copilot
function Projects({ projects }) {
  return (
    <section className="py-16" id="projects">
      <h2 className="text-3xl font-bold">Projects</h2>
      <p className="mt-2 text-dragon-sand/80">Selected builds across LLM reliability, MLOps, and AI systems.</p>
      <div className="mt-8 grid gap-6 md:grid-cols-2">
        {projects.map((project) => (
          <article
            key={project.id}
            className="rounded-2xl border border-dragon-red/25 bg-dragon-navySoft/60 p-6 transition hover:-translate-y-1 hover:border-dragon-redGlow"
          >
            <h3 className="text-xl font-semibold">{project.title}</h3>
            <p className="mt-2 text-dragon-sand/85">{project.description}</p>
            <div className="mt-4 flex flex-wrap gap-2">
              {project.tags.map((tag) => (
                <span
                  key={`${project.id}-${tag}`}
                  className="rounded-full border border-dragon-red/30 px-3 py-1 text-xs"
                >
                  {tag}
                </span>
              ))}
            </div>
            <a
              className="mt-5 inline-block text-sm font-semibold text-dragon-redGlow hover:underline"
              href={project.github}
              target="_blank"
              rel="noreferrer"
            >
              View on GitHub
            </a>
          </article>
        ))}
      </div>
    </section>
  );
}

export default Projects;
