// Generated by GitHub Copilot
import { motion, useReducedMotion } from "framer-motion";

/**
 * Render a premium tactile theme toggle with spring thumb motion and animated track feedback.
 *
 * @param {{
 *   checked: boolean,
 *   onToggle: () => void,
 *   label: string,
 *   hint?: string,
 *   disabled?: boolean,
 * }} props Theme toggle props.
 * @returns {JSX.Element} Animated theme toggle button.
 */
function ThemeToggle({ checked, onToggle, label, hint = "", disabled = false }) {
  const reduceMotion = useReducedMotion();

  const trackVariants = reduceMotion
    ? {
        off: { scaleX: 1, scaleY: 1 },
        on: { scaleX: 1, scaleY: 1 },
      }
    : {
        off: { scaleX: [1, 0.965, 1.015, 1], scaleY: [1, 0.99, 1] },
        on: { scaleX: [1, 0.965, 1.02, 1], scaleY: [1, 0.99, 1] },
      };

  const thumbVariants = {
    off: {
      x: 4,
      rotate: 0,
      scale: 1,
    },
    on: {
      x: 50,
      rotate: 16,
      scale: 1.04,
    },
  };

  const thumbTransition = reduceMotion
    ? { duration: 0 }
    : {
        type: "spring",
        stiffness: 520,
        damping: 22,
        mass: 0.72,
      };

  const thumbCorePulse = reduceMotion
    ? { scale: 1 }
    : checked
      ? { scale: [1, 1.18, 1] }
      : { scale: [1, 1.12, 1] };

  return (
    <motion.button
      type="button"
      onClick={onToggle}
      disabled={disabled}
      className="aurora-toggle"
      data-active={checked ? "true" : "false"}
      role="switch"
      aria-checked={checked}
      aria-label={label}
      title={hint}
      whileTap={reduceMotion ? undefined : { scale: 0.97 }}
    >
      <motion.span
        className="aurora-toggle__track"
        initial={false}
        animate={checked ? "on" : "off"}
        variants={trackVariants}
        transition={{
          duration: reduceMotion ? 0 : 0.44,
          times: reduceMotion ? undefined : [0, 0.4, 0.75, 1],
          ease: "easeOut",
        }}
      >
        <span className="aurora-toggle__sweep" aria-hidden="true" />

        <span className="aurora-toggle__icon aurora-toggle__icon--sun" aria-hidden="true">
          <svg viewBox="0 0 24 24" className="h-3.5 w-3.5" fill="none" stroke="currentColor" strokeWidth="2">
            <circle cx="12" cy="12" r="4" />
            <path d="M12 2v2" />
            <path d="M12 20v2" />
            <path d="M4.93 4.93l1.41 1.41" />
            <path d="M17.66 17.66l1.41 1.41" />
            <path d="M2 12h2" />
            <path d="M20 12h2" />
            <path d="M4.93 19.07l1.41-1.41" />
            <path d="M17.66 6.34l1.41-1.41" />
          </svg>
        </span>

        <span className="aurora-toggle__icon aurora-toggle__icon--moon" aria-hidden="true">
          <svg viewBox="0 0 24 24" className="h-3.5 w-3.5" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
          </svg>
        </span>

        <motion.span
          className="aurora-toggle__thumb"
          initial={false}
          animate={checked ? "on" : "off"}
          variants={thumbVariants}
          transition={thumbTransition}
        >
          <motion.span
            className="aurora-toggle__thumb-core"
            initial={false}
            animate={thumbCorePulse}
            transition={{
              duration: reduceMotion ? 0 : 0.36,
              times: reduceMotion ? undefined : [0, 0.56, 1],
              ease: "easeOut",
            }}
          />
        </motion.span>
      </motion.span>
    </motion.button>
  );
}

export default ThemeToggle;