// Generated by GitHub Copilot
import { describe, expect, it } from "vitest";
import { buildApiUrl } from "./api";

describe("buildApiUrl", () => {
  it("joins base URL and relative path", () => {
    expect(buildApiUrl("profile", "http://127.0.0.1:8080/api")).toBe(
      "http://127.0.0.1:8080/api/profile"
    );
  });

  it("handles trailing slash and leading slash safely", () => {
    expect(buildApiUrl("/chat", "https://api.example.com/")).toBe("https://api.example.com/chat");
  });
});
