// Generated by GitHub Copilot
import { describe, expect, it } from "vitest";
import { buildApiUrl } from "./api";

describe("buildApiUrl", () => {
  it("joins base URL and relative path", () => {
    expect(buildApiUrl("profile", "http://127.0.0.1:8080/api")).toBe(
      "http://127.0.0.1:8080/api/profile"
    );
  });

  it("handles trailing slash and leading slash safely", () => {
    expect(buildApiUrl("/chat", "https://api.example.com/")).toBe("https://api.example.com/chat");
  });

  it("produces a root-relative path when the base URL is empty", () => {
    expect(buildApiUrl("profile", "")).toBe("/profile");
  });

  it("preserves multi-segment endpoint paths", () => {
    expect(buildApiUrl("v1/chat/stream", "https://api.example.com/api/")).toBe(
      "https://api.example.com/api/v1/chat/stream"
    );
  });
});
