// Generated by GitHub Copilot
import { describe, expect, it } from "vitest";
import {
  VISITOR_MODES,
  buildLocalPortfolioReply,
  buildModeSystemPrompt,
  getInitialAssistantMessage,
  normalizeVisitorMode,
} from "./chatRuntime";

describe("chatRuntime", () => {
  it("normalizes visitor mode values", () => {
    expect(normalizeVisitorMode("HIRING")).toBe(VISITOR_MODES.HIRING);
    expect(normalizeVisitorMode(" browsing ")).toBe(VISITOR_MODES.BROWSING);
    expect(normalizeVisitorMode("unknown-mode")).toBe("");
  });

  it("builds mode-aware system prompts", () => {
    const hiringPrompt = buildModeSystemPrompt("Base prompt.", VISITOR_MODES.HIRING);
    const browsingPrompt = buildModeSystemPrompt("Base prompt.", VISITOR_MODES.BROWSING);

    expect(hiringPrompt).toContain("Visitor intent is hiring");
    expect(browsingPrompt).toContain("Visitor intent is browsing");
  });

  it("returns mode-specific intro messages", () => {
    expect(getInitialAssistantMessage("Welcome", VISITOR_MODES.HIRING)).toContain("Hiring mode is active");
    expect(getInitialAssistantMessage("Welcome", VISITOR_MODES.BROWSING)).toContain(
      "Browsing mode is active"
    );
  });

  it("returns factual browsing answers", () => {
    const reply = buildLocalPortfolioReply("What certifications does Ram have?", VISITOR_MODES.BROWSING);
    expect(reply).toContain("Certifications include:");
  });

  it("returns recruiter-oriented hiring answers", () => {
    const reply = buildLocalPortfolioReply("Why should we hire Ram for this role?", VISITOR_MODES.HIRING);
    expect(reply).toContain("Hiring snapshot:");
    expect(reply).toContain("Evidence:");
  });

  it("handles hiring compensation questions safely", () => {
    const reply = buildLocalPortfolioReply("What is his expected salary?", VISITOR_MODES.HIRING);
    expect(reply).toContain("Compensation expectations");
  });
});
