// Generated by GitHub Copilot
import { describe, expect, it } from "vitest";
import {
  VISITOR_MODES,
  buildLocalPortfolioReply,
  buildModeSystemPrompt,
  getInitialAssistantMessage,
  normalizeVisitorMode,
} from "./chatRuntime";

describe("chatRuntime", () => {
  it("normalizes visitor mode values", () => {
    expect(normalizeVisitorMode("HIRING")).toBe(VISITOR_MODES.HIRING);
    expect(normalizeVisitorMode(" browsing ")).toBe(VISITOR_MODES.BROWSING);
    expect(normalizeVisitorMode("unknown-mode")).toBe("");
  });

  it("builds mode-aware system prompts", () => {
    const hiringPrompt = buildModeSystemPrompt("Base prompt.", VISITOR_MODES.HIRING);
    const browsingPrompt = buildModeSystemPrompt("Base prompt.", VISITOR_MODES.BROWSING);

    expect(hiringPrompt).toContain("Visitor intent is hiring");
    expect(browsingPrompt).toContain("Visitor intent is browsing");
  });

  it("returns mode-specific intro messages", () => {
    expect(getInitialAssistantMessage("Welcome", VISITOR_MODES.HIRING)).toContain("Hiring mode is active");
    expect(getInitialAssistantMessage("Welcome", VISITOR_MODES.BROWSING)).toContain(
      "Browsing mode is active"
    );
  });

  it("returns factual browsing answers", () => {
    const reply = buildLocalPortfolioReply("What certifications does Ram have?", VISITOR_MODES.BROWSING);
    expect(reply).toContain("Certifications include:");
  });

  it("returns recruiter-oriented hiring answers", () => {
    const reply = buildLocalPortfolioReply("Why should we hire Ram for this role?", VISITOR_MODES.HIRING);
    expect(reply).toContain("Hiring snapshot:");
    expect(reply).toContain("Evidence:");
  });

  it("handles hiring compensation questions safely", () => {
    const reply = buildLocalPortfolioReply("What is his expected salary?", VISITOR_MODES.HIRING);
    expect(reply).toContain("Compensation expectations");
  });

  it("normalizes non-string visitor mode inputs to an empty string", () => {
    expect(normalizeVisitorMode(null)).toBe("");
    expect(normalizeVisitorMode(undefined)).toBe("");
    expect(normalizeVisitorMode(123)).toBe("");
    expect(normalizeVisitorMode({})).toBe("");
  });

  it("defaults to a browsing prompt and base text when inputs are missing", () => {
    const prompt = buildModeSystemPrompt(undefined, undefined);
    expect(prompt).toContain("You are a concise assistant");
    expect(prompt).toContain("Visitor intent is browsing");
  });

  it("clamps oversized base prompts to a safe length", () => {
    const prompt = buildModeSystemPrompt("x".repeat(600), VISITOR_MODES.BROWSING);
    expect(prompt.startsWith("x".repeat(500))).toBe(true);
    expect(prompt.includes("x".repeat(501))).toBe(false);
  });

  it("falls back to the configured intro message when no mode is selected", () => {
    expect(getInitialAssistantMessage("Welcome aboard", undefined)).toBe("Welcome aboard");
    expect(getInitialAssistantMessage(undefined, "unknown")).toContain("hiring or just browsing");
  });

  it("does not expose the compensation guard in browsing mode", () => {
    const reply = buildLocalPortfolioReply("What is his expected salary?", VISITOR_MODES.BROWSING);
    expect(reply).not.toContain("Compensation expectations");
  });
});
