// Generated by GitHub Copilot
import { beforeEach, describe, expect, it, vi } from "vitest";
import { getTheme, setTheme, wireThemeToggle } from "./theme";

describe("theme utilities", () => {
  beforeEach(() => {
    const setAttribute = vi.fn();
    global.document = {
      documentElement: {
        setAttribute,
      },
    };

    const storage = new Map();
    global.localStorage = {
      getItem: vi.fn((key) => storage.get(key) ?? null),
      setItem: vi.fn((key, value) => {
        storage.set(key, value);
      }),
    };
  });

  it("setTheme applies data-theme and persists preference", () => {
    setTheme("light");

    expect(global.document.documentElement.setAttribute).toHaveBeenCalledWith("data-theme", "light");
    expect(global.localStorage.setItem).toHaveBeenCalledWith("theme", "light");
  });

  it("getTheme returns valid persisted mode and falls back to dark", () => {
    global.localStorage.getItem = vi.fn(() => "system");
    expect(getTheme()).toBe("system");

    global.localStorage.getItem = vi.fn(() => "invalid");
    expect(getTheme()).toBe("dark");
  });

  it("wireThemeToggle registers click handlers for available buttons", () => {
    const listeners = { light: null, dark: null, system: null };
    const light = {
      addEventListener: vi.fn((_event, handler) => {
        listeners.light = handler;
      }),
    };
    const dark = {
      addEventListener: vi.fn((_event, handler) => {
        listeners.dark = handler;
      }),
    };
    const system = {
      addEventListener: vi.fn((_event, handler) => {
        listeners.system = handler;
      }),
    };

    wireThemeToggle(light, dark, system);

    expect(light.addEventListener).toHaveBeenCalledWith("click", expect.any(Function));
    expect(dark.addEventListener).toHaveBeenCalledWith("click", expect.any(Function));
    expect(system.addEventListener).toHaveBeenCalledWith("click", expect.any(Function));

    listeners.light();
    listeners.dark();
    listeners.system();

    expect(global.localStorage.setItem).toHaveBeenNthCalledWith(1, "theme", "light");
    expect(global.localStorage.setItem).toHaveBeenNthCalledWith(2, "theme", "dark");
    expect(global.localStorage.setItem).toHaveBeenNthCalledWith(3, "theme", "system");
  });
});
