// Generated by GitHub Copilot
import Hero from "./components/Hero";
import Projects from "./components/Projects";
import About from "./components/About";
import Contact from "./components/Contact";
import Chatbot from "./components/Chatbot";
import projects from "./data/projects.json";

function App() {
  return (
    <div className="min-h-screen bg-dragon-navy text-dragon-sand font-display">
      <main className="mx-auto max-w-6xl px-4 pb-16 md:px-8">
        <Hero />
        <Projects projects={projects} />
        <About />
        <Contact />
      </main>
      <Chatbot />
    </div>
  );
}

export default App;
