// Generated by GitHub Copilot
import { useMemo } from "react";
import Hero from "./components/Hero";
import Projects from "./components/Projects";
import About from "./components/About";
import Insights from "./components/Insights";
import Contact from "./components/Contact";
import Chatbot from "./components/Chatbot";
import usePortfolioData from "./hooks/usePortfolioData";
import { siteConfig } from "./config/siteConfig";
import projects from "./data/projects.json";

function App() {
  const { data: profileData, loading, error } = usePortfolioData();

  /**
   * Convert live GitHub repositories into project cards with static fallback.
   */
  const projectCards = useMemo(() => {
    if (profileData?.github?.repos?.length) {
      return profileData.github.repos.map((repo) => ({
        id: repo.id,
        title: repo.title,
        description: repo.description,
        tags: repo.tags,
        github: repo.github,
        stars: repo.stars,
        forks: repo.forks,
      }));
    }

    return projects;
  }, [profileData]);

  return (
    <div className="min-h-screen bg-dragon-navy text-dragon-sand font-body">
      <main className="mx-auto max-w-6xl px-4 pb-16 md:px-8">
        {error ? (
          <div className="mt-4 rounded-xl border border-dragon-red/35 bg-dragon-navySoft/70 px-4 py-3 text-sm text-dragon-sand/90">
            {error}
          </div>
        ) : null}

        <Hero config={siteConfig.identity} profile={profileData} loading={loading} />
        <Projects projects={projectCards} config={siteConfig.projects} />
        <About config={siteConfig.about} profile={profileData} />
        <Insights profile={profileData} />
        <Contact config={siteConfig.contact} apiBaseUrl={siteConfig.api.baseUrl} />
      </main>
      {siteConfig.chat.enabled ? (
        <Chatbot config={siteConfig.chat} apiBaseUrl={siteConfig.api.baseUrl} />
      ) : null}
    </div>
  );
}

export default App;
